### ISSUE TITLE
telegraf runtime error due to docker issue

### ISSUE THREAD

**Issue by derekpurdy** [sabuto/hassio-telegraf#54]
#Type of Issue
<!--- Is this a feature request or an issue? ---!>
Issue

#Description of issue
```
panic: runtime error: slice bounds out of range [:4] with capacity 0
goroutine 111 [running]:
github.com/influxdata/telegraf/plugins/inputs/docker.parseContainerStats(0x40000d2d80, 0x2c9f480, 0x40001163a0, 0x4000d766c0, 0x400063d700, 0x40, 0x1, 0x4000232051, 0x5)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:677 +0x1c00
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).gatherContainerInspect(0x40001ea000, 0x400063d700, 0x40, 0x4000bf1400, 0x1, 0x4, 0x400063d740, 0x38, 0x40005e8730, 0x47, ...)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:568 +0x1c4
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).gatherContainer(0x40001ea000, 0x400063d700, 0x40, 0x4000bf1400, 0x1, 0x4, 0x400063d740, 0x38, 0x40005e8730, 0x47, ...)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:495 +0x6b4
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather.func1(0x4000d73c80, 0x40001ea000, 0x2c9f480, 0x40001163a0, 0x400063d700, 0x40, 0x4000bf1400, 0x1, 0x4, 0x400063d740, ...)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:217 +0x84
created by github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather
	/go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:215 +0x2d8
```

#Ideas to fix
<!--- if you have nay ideas to fix this issue please specify them here ---!>

This was fixed in a newer version of telegraf
https://github.com/influxdata/telegraf/issues/8692

# Logs
<!--- please past the logs here ---!>

**Comment by sabuto** [comment]
I have updated telegraf the the latests version, let me know if it happens again
